In [7]:
import os
from pathlib import Path

import numpy as np
import pandas as pd

In [8]:
#   import warnings
#   
#   warnings.filterwarnings("ignore")

In [9]:
cwd = Path.cwd().resolve()

if cwd.name == "notebooks":
    PROJECT_DIR = cwd.parent
else:
    PROJECT_DIR = cwd

print("Project dir:", PROJECT_DIR.name)
print("Working dir:", cwd.name)

Project dir: 2026-03_taxi-trip-chicago
Working dir: notebooks

In [ ]:
DATA_RAW = PROJECT_DIR / "data" / "raw"
DATA_STAGING = PROJECT_DIR / "data" / "staging"
DATA_PROCESSED = PROJECT_DIR / "data" / "processed"

TRIPS_FILE = DATA_RAW / "Taxi_Trips_20260324.csv"

In [11]:
df = pd.read_csv(TRIPS_FILE)
print("trips shape:", df.shape)
df.head()

trips shape: (14219363, 23)

,Trip ID,Taxi ID,Trip Start Timestamp,Trip End Timestamp,Trip Seconds,Trip Miles,Pickup Census Tract,Dropoff Census Tract,Pickup Community Area,Dropoff Community Area,...,Extras,Trip Total,Payment Type,Company,Pickup Centroid Latitude,Pickup Centroid Longitude,Pickup Centroid Location,Dropoff Centroid Latitude,Dropoff Centroid Longitude,Dropoff Centroid Location
0,0000184e7cd53cee95af32eba49c44e4d20adcd8,f538e6b729d1aaad4230e9dcd9dc2fd9a168826ddadbd6...,01/19/2024 05:00:00 PM,01/19/2024 06:00:00 PM,4051.0,17.12,1.703198e+10,1.703132e+10,76.0,32.0,...,4.0,60.00,Credit Card,Flash Cab,41.979071,-87.903040,POINT (-87.9030396611 41.9790708201),41.884987,-87.620993,POINT (-87.6209929134 41.8849871918)
1,000072ee076c9038868e239ca54185eb43959db0,e51e2c30caec952b40b8329a68b498e18ce8a1f40fa75c...,01/28/2024 02:30:00 PM,01/28/2024 03:00:00 PM,1749.0,12.70,NaN,NaN,6.0,NaN,...,0.0,33.75,Cash,Flash Cab,41.944227,-87.655998,POINT (-87.6559981815 41.9442266014),NaN,NaN,NaN
2,000074019d598c2b1d6e77fbae79e40b0461a2fc,aeb280ef3be3e27e081eb6e76027615b0d40925b84d3eb...,01/05/2024 09:00:00 AM,01/05/2024 09:00:00 AM,517.0,3.39,NaN,NaN,6.0,8.0,...,1.0,14.69,Mobile,Taxicab Insurance Agency Llc,41.944227,-87.655998,POINT (-87.6559981815 41.9442266014),41.899602,-87.633308,POINT (-87.6333080367 41.899602111)
3,00007572c5f92e2ff067e6f838a5ad74e83665d3,7d21c2ca227db8f27dda96612bfe5520ab408fa9a462c8...,01/22/2024 08:45:00 AM,01/22/2024 09:30:00 AM,2050.0,15.06,NaN,NaN,76.0,NaN,...,5.5,56.56,Credit Card,Globe Taxi,41.980264,-87.913625,POINT (-87.913624596 41.9802643146),NaN,NaN,NaN
4,00007c3e7546e2c7d15168586943a9c22c3856cf,8ef1056519939d511d24008e394f83e925d2539d668a00...,01/18/2024 07:15:00 PM,01/18/2024 07:30:00 PM,1004.0,1.18,1.703184e+10,1.703184e+10,32.0,32.0,...,0.0,19.66,Mobile,5 Star Taxi,41.880994,-87.632746,POINT (-87.6327464887 41.8809944707),41.880994,-87.632746,POINT (-87.6327464887 41.8809944707)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14219363 entries, 0 to 14219362
Data columns (total 23 columns):
 #   Column                      Dtype
---  ------                      -----
 0   Trip ID                     object
 1   Taxi ID                     object
 2   Trip Start Timestamp        object
 3   Trip End Timestamp          object
 4   Trip Seconds                float64
 5   Trip Miles                  float64
 6   Pickup Census Tract         float64
 7   Dropoff Census Tract        float64
 8   Pickup Community Area       float64
 9   Dropoff Community Area      float64
 10  Fare                        float64
 11  Tips                        float64
 12  Tolls                       float64
 13  Extras                      float64
 14  Trip Total                  float64
 15  Payment Type                object
 16  Company                     object
 17  Pickup Centroid Latitude    float64
 18  Pickup Centroid Longitude   float64
 19  Pickup Centroid Location    object
 20  Dropoff Centroid Latitude   float64
 21  Dropoff Centroid Longitude  float64
 22  Dropoff Centroid  Location  object
dtypes: float64(15), object(8)
memory usage: 2.4+ GB

quito espacios de nombres de columnas

In [13]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace(".", "", regex=False)
)

In [14]:
df.columns

Index(['trip_id', 'taxi_id', 'trip_start_timestamp', 'trip_end_timestamp',
       'trip_seconds', 'trip_miles', 'pickup_census_tract',
       'dropoff_census_tract', 'pickup_community_area',
       'dropoff_community_area', 'fare', 'tips', 'tolls', 'extras',
       'trip_total', 'payment_type', 'company', 'pickup_centroid_latitude',
       'pickup_centroid_longitude', 'pickup_centroid_location',
       'dropoff_centroid_latitude', 'dropoff_centroid_longitude',
       'dropoff_centroid__location'],
      dtype='object')

dropoff_centroid_location viene con dos guines bajos, se modifica puntual ese nombre

In [15]:
df = df.rename(columns={
    "dropoff_centroid__location": "dropoff_centroid_location"
})

formato a fechas

In [16]:
df["trip_start_timestamp"] = pd.to_datetime(
    df["trip_start_timestamp"],
    format="%m/%d/%Y %I:%M:%S %p",
    errors="coerce"
)

df["trip_end_timestamp"] = pd.to_datetime(
    df["trip_end_timestamp"],
    format="%m/%d/%Y %I:%M:%S %p",
    errors="coerce"
)

In [17]:
df[["trip_start_timestamp", "trip_end_timestamp"]].head()

  trip_start_timestamp  trip_end_timestamp
0  2024-01-19 17:00:00 2024-01-19 18:00:00
1  2024-01-28 14:30:00 2024-01-28 15:00:00
2  2024-01-05 09:00:00 2024-01-05 09:00:00
3  2024-01-22 08:45:00 2024-01-22 09:30:00
4  2024-01-18 19:15:00 2024-01-18 19:30:00

In [18]:
cols_num = [
    "trip_seconds",
    "trip_miles",
    "fare",
    "tips",
    "tolls",
    "extras",
    "trip_total",
    "pickup_centroid_latitude",
    "pickup_centroid_longitude",
    "dropoff_centroid_latitude",
    "dropoff_centroid_longitude"
]

for c in cols_num:
    df[c] = pd.to_numeric(df[c], errors="coerce")

In [19]:
cols_id_geo = [
    "pickup_census_tract",
    "dropoff_census_tract",
    "pickup_community_area",
    "dropoff_community_area"
]

for c in cols_id_geo:
    df[c] = pd.to_numeric(df[c], errors="coerce")

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14219363 entries, 0 to 14219362
Data columns (total 23 columns):
 #   Column                      Dtype
---  ------                      -----
 0   trip_id                     object
 1   taxi_id                     object
 2   trip_start_timestamp        datetime64[ns]
 3   trip_end_timestamp          datetime64[ns]
 4   trip_seconds                float64
 5   trip_miles                  float64
 6   pickup_census_tract         float64
 7   dropoff_census_tract        float64
 8   pickup_community_area       float64
 9   dropoff_community_area      float64
 10  fare                        float64
 11  tips                        float64
 12  tolls                       float64
 13  extras                      float64
 14  trip_total                  float64
 15  payment_type                object
 16  company                     object
 17  pickup_centroid_latitude    float64
 18  pickup_centroid_longitude   float64
 19  pickup_centroid_location    object
 20  dropoff_centroid_latitude   float64
 21  dropoff_centroid_longitude  float64
 22  dropoff_centroid_location   object
dtypes: datetime64[ns](2), float64(15), object(6)
memory usage: 2.4+ GB

In [21]:
df.head()

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_census_tract,dropoff_census_tract,pickup_community_area,dropoff_community_area,...,extras,trip_total,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,pickup_centroid_location,dropoff_centroid_latitude,dropoff_centroid_longitude,dropoff_centroid_location
0,0000184e7cd53cee95af32eba49c44e4d20adcd8,f538e6b729d1aaad4230e9dcd9dc2fd9a168826ddadbd6...,2024-01-19 17:00:00,2024-01-19 18:00:00,4051.0,17.12,1.703198e+10,1.703132e+10,76.0,32.0,...,4.0,60.00,Credit Card,Flash Cab,41.979071,-87.903040,POINT (-87.9030396611 41.9790708201),41.884987,-87.620993,POINT (-87.6209929134 41.8849871918)
1,000072ee076c9038868e239ca54185eb43959db0,e51e2c30caec952b40b8329a68b498e18ce8a1f40fa75c...,2024-01-28 14:30:00,2024-01-28 15:00:00,1749.0,12.70,NaN,NaN,6.0,NaN,...,0.0,33.75,Cash,Flash Cab,41.944227,-87.655998,POINT (-87.6559981815 41.9442266014),NaN,NaN,NaN
2,000074019d598c2b1d6e77fbae79e40b0461a2fc,aeb280ef3be3e27e081eb6e76027615b0d40925b84d3eb...,2024-01-05 09:00:00,2024-01-05 09:00:00,517.0,3.39,NaN,NaN,6.0,8.0,...,1.0,14.69,Mobile,Taxicab Insurance Agency Llc,41.944227,-87.655998,POINT (-87.6559981815 41.9442266014),41.899602,-87.633308,POINT (-87.6333080367 41.899602111)
3,00007572c5f92e2ff067e6f838a5ad74e83665d3,7d21c2ca227db8f27dda96612bfe5520ab408fa9a462c8...,2024-01-22 08:45:00,2024-01-22 09:30:00,2050.0,15.06,NaN,NaN,76.0,NaN,...,5.5,56.56,Credit Card,Globe Taxi,41.980264,-87.913625,POINT (-87.913624596 41.9802643146),NaN,NaN,NaN
4,00007c3e7546e2c7d15168586943a9c22c3856cf,8ef1056519939d511d24008e394f83e925d2539d668a00...,2024-01-18 19:15:00,2024-01-18 19:30:00,1004.0,1.18,1.703184e+10,1.703184e+10,32.0,32.0,...,0.0,19.66,Mobile,5 Star Taxi,41.880994,-87.632746,POINT (-87.6327464887 41.8809944707),41.880994,-87.632746,POINT (-87.6327464887 41.8809944707)

In [22]:
df.isna().sum().sort_values(ascending=False)

dropoff_census_tract          8113518
pickup_census_tract           7922844
dropoff_community_area        1272573
dropoff_centroid_longitude    1196124
dropoff_centroid_location     1196124
dropoff_centroid_latitude     1196124
pickup_community_area          397311
pickup_centroid_location       390023
pickup_centroid_latitude       390023
pickup_centroid_longitude      390023
trip_total                      30499
fare                            30499
extras                          30499
tolls                           30499
tips                            30499
trip_seconds                     2649
trip_end_timestamp                189
trip_miles                        119
taxi_id                            11
trip_id                             0
trip_start_timestamp                0
payment_type                        0
company                             0
dtype: int64

In [23]:
(df.isna().mean() * 100).sort_values(ascending=False).round(2)

dropoff_census_tract          57.06
pickup_census_tract           55.72
dropoff_community_area         8.95
dropoff_centroid_longitude     8.41
dropoff_centroid_location      8.41
dropoff_centroid_latitude      8.41
pickup_community_area          2.79
pickup_centroid_location       2.74
pickup_centroid_latitude       2.74
pickup_centroid_longitude      2.74
trip_total                     0.21
fare                           0.21
extras                         0.21
tolls                          0.21
tips                           0.21
trip_seconds                   0.02
trip_end_timestamp             0.00
trip_miles                     0.00
taxi_id                        0.00
trip_id                        0.00
trip_start_timestamp           0.00
payment_type                   0.00
company                        0.00
dtype: float64

se crean nuevas variables

In [24]:
df["trip_date"] = df["trip_start_timestamp"].dt.date
df["trip_year"] = df["trip_start_timestamp"].dt.year
df["trip_month"] = df["trip_start_timestamp"].dt.month
df["trip_day"] = df["trip_start_timestamp"].dt.day
df["trip_hour"] = df["trip_start_timestamp"].dt.hour
df["trip_weekday"] = df["trip_start_timestamp"].dt.day_name()
df["trip_weekday_num"] = df["trip_start_timestamp"].dt.weekday

df["is_weekend"] = df["trip_weekday_num"].isin([5, 6])

In [25]:
df[["trip_start_timestamp", "trip_date", "trip_year", "trip_month", "trip_hour", "trip_weekday", "trip_weekday_num"]].head()

,trip_start_timestamp,trip_date,trip_year,trip_month,trip_hour,trip_weekday,trip_weekday_num
0,2024-01-19 17:00:00,2024-01-19,2024,1,17,Friday,4
1,2024-01-28 14:30:00,2024-01-28,2024,1,14,Sunday,6
2,2024-01-05 09:00:00,2024-01-05,2024,1,9,Friday,4
3,2024-01-22 08:45:00,2024-01-22,2024,1,8,Monday,0
4,2024-01-18 19:15:00,2024-01-18,2024,1,19,Thursday,3

In [26]:
df[["trip_seconds", "trip_miles", "fare", "tips", "tolls", "extras", "trip_total"]].describe()

,trip_seconds,trip_miles,fare,tips,tolls,extras,trip_total
count,1.421671e+07,1.421924e+07,1.418886e+07,1.418886e+07,1.418886e+07,1.418886e+07,1.418886e+07
mean,1.225905e+03,6.567188e+00,2.246990e+01,2.770886e+00,3.059485e-02,2.033563e+00,2.754610e+01
std,1.610112e+03,7.600035e+00,3.317939e+01,4.236935e+00,3.815459e+00,8.786831e+00,3.744949e+01
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,4.800000e+02,1.070000e+00,8.500000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.025000e+01
50%,9.000000e+02,3.060000e+00,1.500000e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.778000e+01
75%,1.663000e+03,1.165000e+01,3.375000e+01,4.000000e+00,0.000000e+00,1.500000e+00,4.120000e+01
max,8.640000e+04,3.397800e+03,9.999750e+03,7.507500e+02,5.550000e+03,5.559500e+03,9.999750e+03

In [27]:
df["trip_start_timestamp"].min(), df["trip_start_timestamp"].max()

(Timestamp('2024-01-01 00:00:00'), Timestamp('2026-03-01 00:00:00'))

In [28]:
df["flag_monto"] = df["fare"].notna()

df["flag_pickup_geo"] = (
    df["pickup_community_area"].notna() |
    df["pickup_centroid_latitude"].notna() |
    df["pickup_centroid_longitude"].notna()
)

df["flag_dropoff_geo"] = (
    df["dropoff_community_area"].notna() |
    df["dropoff_centroid_latitude"].notna() |
    df["dropoff_centroid_longitude"].notna()
)

In [29]:
df[["flag_monto", "flag_pickup_geo", "flag_dropoff_geo"]].head()

   flag_monto  flag_pickup_geo  flag_dropoff_geo
0        True             True              True
1        True             True             False
2        True             True              True
3        True             True             False
4        True             True              True

In [30]:
df["trip_minutes"] = df["trip_seconds"] / 60
df["trip_hours"] = df["trip_seconds"] / 3600

In [31]:
df["total_calculado"] = df["fare"] + df["tips"] + df["tolls"] + df["extras"]

In [33]:
#   df["diff_total"] = df["trip_total"] - df["total_calculado"]

In [34]:
# df["flag_total_consistente"] = df["diff_total"].abs() <= 0.01

In [35]:
# df["flag_total_consistente"].mean()

In [36]:
df["speed_mph"] = df["trip_miles"] / df["trip_hours"]

In [37]:
df["fare_per_mile"] = df["fare"] / df["trip_miles"]

In [38]:
df["trip_total_per_mile"] = df["trip_total"] / df["trip_miles"]

In [39]:
df["fare_per_minute"] = df["fare"] / df["trip_minutes"]

In [40]:
df["trip_total_per_minute"] = df["trip_total"] / df["trip_minutes"]

In [41]:
import numpy as np

cols_ratio = [
    "speed_mph",
    "fare_per_mile",
    "trip_total_per_mile",
    "fare_per_minute",
    "trip_total_per_minute"
]

for c in cols_ratio:
    df[c] = df[c].replace([np.inf, -np.inf], np.nan)

In [42]:
df["tip_pct"] = (df["tips"] / df["fare"]) * 100
df["tip_pct"] = df["tip_pct"].replace([np.inf, -np.inf], np.nan)

el viaje tiene el núcleo mínimo para análisis operativo:

inicio + duración + distancia

In [43]:
df["flag_trip_core"] = (
    df["trip_seconds"].notna() &
    df["trip_miles"].notna() &
    df["trip_start_timestamp"].notna()
)

In [44]:
df["time_band"] = "night"

df.loc[df["trip_hour"].between(6, 11), "time_band"] = "morning"
df.loc[df["trip_hour"].between(12, 17), "time_band"] = "afternoon"
df.loc[df["trip_hour"].between(18, 23), "time_band"] = "evening"

In [46]:
df[
    [
        "trip_year", "trip_month", "trip_hour", "is_weekend", "time_band",
        "trip_minutes", "trip_hours", "total_calculado", "speed_mph", "fare_per_mile",
        "trip_total_per_mile", "fare_per_minute", "trip_total_per_minute",
        "tip_pct", "flag_trip_core"
    ]
].head()

,trip_year,trip_month,trip_hour,is_weekend,time_band,trip_minutes,trip_hours,total_calculado,speed_mph,fare_per_mile,trip_total_per_mile,fare_per_minute,trip_total_per_minute,tip_pct,flag_trip_core
0,2024,1,17,False,afternoon,67.516667,1.125278,59.50,15.214021,2.657710,3.504673,0.673908,0.888669,21.978022,True
1,2024,1,14,True,afternoon,29.150000,0.485833,33.75,26.140652,2.657480,2.657480,1.157804,1.157804,0.000000,True
2,2024,1,9,False,morning,8.616667,0.143611,14.69,23.605416,3.218289,4.333333,1.266151,1.704836,25.481210,True
3,2024,1,8,False,morning,34.166667,0.569444,56.06,26.446829,2.606242,3.755644,1.148780,1.655415,28.815287,True
4,2024,1,19,False,evening,16.733333,0.278889,19.66,4.231076,13.508475,16.661017,0.952590,1.174900,23.337516,True

In [48]:
df[
    [
        "trip_minutes", "trip_hours", "speed_mph",
        "fare_per_mile", "trip_total_per_mile", "fare_per_minute",
        "trip_total_per_minute", "tip_pct"
    ]
].describe()

,trip_minutes,trip_hours,speed_mph,fare_per_mile,trip_total_per_mile,fare_per_minute,trip_total_per_minute,tip_pct
count,1.421671e+07,1.421671e+07,1.402146e+07,1.293828e+07,1.293828e+07,1.399218e+07,1.399218e+07,1.415224e+07
mean,2.043176e+01,3.405293e-01,1.759367e+01,1.376095e+01,1.778216e+01,1.215641e+01,1.459689e+01,1.379367e+01
std,2.683520e+01,4.472533e-01,1.747083e+02,1.774354e+02,2.224980e+02,2.122776e+02,2.191977e+02,1.666939e+02
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,8.000000e+00,1.333333e-01,8.400000e+00,2.685811e+00,3.300000e+00,8.230453e-01,9.508887e-01,0.000000e+00
50%,1.500000e+01,2.500000e-01,1.338215e+01,3.688525e+00,4.444444e+00,1.041667e+00,1.241026e+00,0.000000e+00
75%,2.771667e+01,4.619444e-01,2.395030e+01,5.973451e+00,7.148936e+00,1.393189e+00,1.723529e+00,2.274809e+01
max,1.440000e+03,2.400000e+01,4.233044e+05,1.020500e+05,1.020500e+05,2.265000e+05,2.265000e+05,2.650000e+05

In [49]:
df.columns

Index(['trip_id', 'taxi_id', 'trip_start_timestamp', 'trip_end_timestamp',
       'trip_seconds', 'trip_miles', 'pickup_census_tract',
       'dropoff_census_tract', 'pickup_community_area',
       'dropoff_community_area', 'fare', 'tips', 'tolls', 'extras',
       'trip_total', 'payment_type', 'company', 'pickup_centroid_latitude',
       'pickup_centroid_longitude', 'pickup_centroid_location',
       'dropoff_centroid_latitude', 'dropoff_centroid_longitude',
       'dropoff_centroid_location', 'trip_date', 'trip_year', 'trip_month',
       'trip_day', 'trip_hour', 'trip_weekday', 'trip_weekday_num',
       'is_weekend', 'flag_monto', 'flag_pickup_geo', 'flag_dropoff_geo',
       'trip_minutes', 'trip_hours', 'total_calculado', 'speed_mph',
       'fare_per_mile', 'trip_total_per_mile', 'fare_per_minute',
       'trip_total_per_minute', 'tip_pct', 'flag_trip_core', 'time_band'],
      dtype='object')

In [50]:
df.loc[df["trip_hours"] <= 0, "speed_mph"] = np.nan

df.loc[df["trip_miles"] <= 0, "fare_per_mile"] = np.nan
df.loc[df["trip_miles"] <= 0, "trip_total_per_mile"] = np.nan

df.loc[df["trip_minutes"] <= 0, "fare_per_minute"] = np.nan
df.loc[df["trip_minutes"] <= 0, "trip_total_per_minute"] = np.nan

df.loc[df["fare"] <= 0, "tip_pct"] = np.nan

análisis de duplicados

In [51]:
df["trip_id"].duplicated().sum()

np.int64(0)

In [52]:
df.duplicated(subset=["taxi_id", "trip_start_timestamp", "trip_end_timestamp"]).sum()

np.int64(170793)

In [53]:
cols = [
    "trip_seconds",
    "trip_miles",
    "fare",
    "tips",
    "tolls",
    "extras",
    "trip_total",
    "trip_minutes",
    "trip_hours",
    "speed_mph",
    "fare_per_mile",
    "trip_total_per_mile",
    "fare_per_minute",
    "trip_total_per_minute",
    "tip_pct"
]

df[cols].agg(["min", "max"]).T

                       min            max
trip_seconds           0.0   86400.000000
trip_miles             0.0    3397.800000
fare                   0.0    9999.750000
tips                   0.0     750.750000
tolls                  0.0    5550.000000
extras                 0.0    5559.500000
trip_total             0.0    9999.750000
trip_minutes           0.0    1440.000000
trip_hours             0.0      24.000000
speed_mph              0.0  423304.363636
fare_per_mile          0.0  102050.000000
trip_total_per_mile    0.0  102050.000000
fare_per_minute        0.0  226500.000000
trip_total_per_minute  0.0  226500.000000
tip_pct                0.0  265000.000000

In [54]:
df[cols].describe(percentiles=[0.01, 0.02, 0.05, 0.50, 0.95, 0.98, 0.99]).round(2).T

,count,mean,std,min,1%,2%,5%,50%,95%,98%,99%,max
trip_seconds,14216714.0,1225.91,1610.11,0.0,0.00,4.00,27.00,900.00,3195.00,3965.00,4581.00,86400.00
trip_miles,14219244.0,6.57,7.60,0.0,0.00,0.00,0.00,3.06,18.32,22.09,26.77,3397.80
fare,14188864.0,22.47,33.18,0.0,3.25,3.25,4.50,15.00,52.25,65.25,75.00,9999.75
tips,14188864.0,2.77,4.24,0.0,0.00,0.00,0.00,0.00,11.10,13.90,16.00,750.75
tolls,14188864.0,0.03,3.82,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,5550.00
extras,14188864.0,2.03,8.79,0.0,0.00,0.00,0.00,0.00,6.00,24.00,32.29,5559.50
trip_total,14188864.0,27.55,37.45,0.0,3.25,3.25,5.04,17.78,68.25,85.00,99.90,9999.75
trip_minutes,14216714.0,20.43,26.84,0.0,0.00,0.07,0.45,15.00,53.25,66.08,76.35,1440.00
trip_hours,14216714.0,0.34,0.45,0.0,0.00,0.00,0.01,0.25,0.89,1.10,1.27,24.00
speed_mph,14021457.0,17.59,174.71,0.0,0.00,0.00,0.00,13.38,40.67,46.88,50.60,423304.36
fare_per_mile,12938277.0,13.76,177.44,0.0,2.39,2.43,2.48,3.69,12.50,40.00,85.00,102050.00
trip_total_per_mile,12938277.0,17.78,222.50,0.0,2.50,2.55,2.64,4.44,16.07,46.25,108.33,102050.00
fare_per_minute,13992178.0,12.16,212.28,0.0,0.40,0.51,0.61,1.04,3.85,88.38,370.00,226500.00
trip_total_per_minute,13992178.0,14.60,219.20,0.0,0.42,0.55,0.67,1.24,4.92,143.54,432.86,226500.00
tip_pct,14152244.0,13.79,166.69,0.0,0.00,0.00,0.00,0.00,40.00,55.56,72.73,265000.00

In [55]:
(df["trip_miles"] == 0).sum()

np.int64(1253227)

In [56]:
(df["fare"] == 0).sum()
(df["trip_total"] == 0).sum()

np.int64(34754)

In [57]:
df.sort_values("trip_miles", ascending=False)[
    ["trip_id", "trip_start_timestamp", "trip_seconds", "trip_miles", "fare", "trip_total", "payment_type", "company"]
].head(20)

,trip_id,trip_start_timestamp,trip_seconds,trip_miles,fare,trip_total,payment_type,company
1727058,8bb9ae67ccafb402045fd52e5f2ba31ef2963835,2024-04-21 07:15:00,8092.0,3397.80,67.00,67.00,Cash,Chicago Independents
673741,8656832cf4c4d23c8bbb728f43bd645020b1258f,2024-02-10 10:00:00,27853.0,3093.47,9999.75,9999.75,Cash,Blue Ribbon Taxi Association
2853227,80e84d4e2ee8e03cf26c994714700b6a7eacf4c6,2024-06-25 14:00:00,2313.0,3017.61,44.25,58.50,Credit Card,Sun Taxi
6373816,c0198d5377db37f1508aa57c8a299d18f2c5b566,2024-12-01 09:30:00,14925.0,2949.41,9999.75,9999.75,Cash,Blue Ribbon Taxi Association
2119521,522fc9a30df54459fbee9558749bbd29674ae700,2024-05-28 16:00:00,72.0,2820.67,3.50,6.00,Cash,Flash Cab
5612768,45c7b37478c4cd41b3abe89bbcf390a8eb2fc9ab,2024-11-25 13:45:00,1732.0,2537.51,42.75,56.70,Credit Card,Choice Taxi Association Inc
3616284,65d80b26805e9548766a10a894848f882374660b,2024-08-06 08:30:00,33950.0,2265.43,9999.75,9999.75,Cash,Blue Ribbon Taxi Association
6151458,52c4902403064408e66026dfa323bb13925b5eb7,2024-12-24 00:15:00,1585.0,2166.39,30.00,30.00,Prcard,5 Star Taxi
188038,6e4aecb7dab42a2109ec97a76e408699e2ad0c62,2024-01-31 12:45:00,56.0,1626.85,3668.50,3668.50,Cash,Blue Ribbon Taxi Association
4442294,483cc8023cff3ac64bc40745d35974cd8c99ab92,2024-09-09 10:30:00,11.0,1293.43,5938.00,5938.00,Cash,Blue Ribbon Taxi Association
5742445,8139408b3729602119b3dafc205a7f6debfc28ef,2024-11-06 10:00:00,32809.0,1127.86,5409.25,5409.25,Cash,Blue Ribbon Taxi Association
14005434,89fa43457506e3932925803978a28859423364a6,2026-02-16 13:45:00,8320.0,1122.21,284.00,293.00,Cash,City Service
11642659,1d10b271d35211775ca03876b6224e3d1952b90d,2025-10-20 12:30:00,NaN,1095.07,627.30,627.30,Cash,Flash Cab
123482,484e98b2334acc489a06413eb3cf3a4685c646e4,2024-01-30 14:00:00,56760.0,1081.20,2478.50,2478.50,Cash,Taxi Affiliation Services
4698325,b9a5a8c47abf1e64f9cd9e49a2ceaecf682c19f3,2024-09-24 06:30:00,8095.0,1075.56,5324.00,5324.00,Cash,Blue Ribbon Taxi Association
7727382,af67c4025ac7756c9a77bdfa0293c6bb22933936,2025-04-17 15:45:00,3224.0,979.17,39.75,54.30,Mobile,Blue Ribbon Taxi Association
485363,1bb4ab6104559c7bdb7e35f8fc90429272a4c7df,2024-02-11 16:30:00,NaN,935.02,2107.00,2107.00,Cash,Blue Ribbon Taxi Association
5193755,9145368a4239270f84817555b5939f59b3aebb9c,2024-10-14 18:15:00,NaN,887.22,4578.75,4578.75,Cash,Blue Ribbon Taxi Association
1665101,6e6085f4090111e5f4bdcb4e794795432be184c0,2024-04-01 12:45:00,NaN,826.56,3205.50,3205.50,Cash,Blue Ribbon Taxi Association
3911600,a94a17e9db822420651cedfa436210ab25e7b8be,2024-08-05 14:30:00,1194.0,812.28,20.25,34.13,Credit Card,Sun Taxi

In [58]:
df.sort_values("trip_seconds", ascending=False)[
    ["trip_id", "trip_start_timestamp", "trip_seconds", "trip_miles", "fare", "trip_total", "payment_type", "company"]
].head(20)

,trip_id,trip_start_timestamp,trip_seconds,trip_miles,fare,trip_total,payment_type,company
10395891,0cb6338958a53bc3d1140d6cbfa24533a171c897,2025-08-20 15:00:00,86400.0,0.00,1.00,1.00,Cash,Tac - Checker Cab Dispatch
12164258,ec6c7c71e365fc935278e4e5f0c1f88adbfe9a5f,2025-10-05 17:30:00,86396.0,0.00,25.55,25.55,Cash,Chicago Independents
8123455,5224d3ab360fc1ba9a660f92b7c471bc0383818d,2025-03-19 18:15:00,86396.0,1.47,9.25,10.25,Cash,Taxicab Insurance Agency Llc
1495930,1e10bbfb70b9ac63d8c37f191b8760eae77b4399,2024-04-24 22:15:00,86379.0,15.34,38.75,42.75,Cash,Chicago Independents
1126849,7050303945c2d4a577581455c6e9879bd727a8a0,2024-03-18 12:30:00,86340.0,0.00,49.25,49.75,Credit Card,Globe Taxi
499735,23d18b0c751016ef59fb37394155bc556bd5de59,2024-02-19 16:15:00,86340.0,0.00,40.00,50.62,Credit Card,Globe Taxi
2501090,f2172b25cc39040d56d79d5c2376024acdb4acb2,2024-05-07 23:15:00,86340.0,0.00,10.00,10.50,Credit Card,Globe Taxi
5704468,6fc043c9bf81448058a3df76fb89837db9f6ac31,2024-11-13 21:00:00,86322.0,18.51,47.75,55.75,Cash,Flash Cab
3030978,c8c44e4d09621abefef0d5fbd9ee3d13c7d6515d,2024-06-20 21:00:00,86265.0,10.48,32.25,32.25,Cash,Globe Taxi
12150895,e7278bf9671255e1c70ac89445304cf8a6455e18,2025-10-29 16:45:00,86177.0,0.00,13.00,13.00,Cash,Tac - Yellow Cab Association
9201801,190b6ad45a46d90fd547bd6a96f40c394a911921,2025-06-13 20:45:00,86144.0,241.03,902.25,902.25,Cash,Blue Ribbon Taxi Association
55591,20965e71f44cb0541beea63f5bea9f02357eed90,2024-01-10 15:30:00,86135.0,2.42,38.75,38.75,Cash,Flash Cab
5526904,1e5319a4c87c02b57e883576b05b1de8371e0862,2024-11-03 05:30:00,86078.0,10.46,26.75,26.75,Cash,5 Star Taxi
6811507,b43fa82b87a331338bf76ab381679c37fa2dd82f,2025-01-30 17:45:00,86067.0,4.95,17.00,17.00,Cash,Blue Ribbon Taxi Association
13159951,c2ef045856055d1b61fbebda5ed8685889e1dc75,2025-12-19 18:30:00,86040.0,0.00,10.00,10.50,Credit Card,Globe Taxi
9636045,c49564de3b8debee7242f768bbcbaf6bd68ddbf3,2025-06-15 22:00:00,86036.0,200.10,811.25,811.25,Cash,Blue Ribbon Taxi Association
6466711,edd7f0d9dcfe36d77bb8bf97c58f538e3192a1d7,2024-12-01 13:15:00,85952.0,11.18,32.75,32.75,Cash,Flash Cab
3219354,0b7b615aa8336023a6553649da00a3f541c11a76,2024-08-12 08:30:00,85949.0,3.70,13.25,13.25,Cash,Flash Cab
3987533,baac817fc71ecd293be6337f3629b59ba18b67e1,2024-08-19 11:45:00,85920.0,0.00,3.25,3.25,Cash,Chicago Independents
731768,a7562dae450d2c8bd8f776032aa743d0f8213a83,2024-02-12 10:00:00,85881.0,0.00,11.89,11.89,Cash,Blue Ribbon Taxi Association

In [61]:
dup_taxi_time = df[
    df.duplicated(
        subset=["taxi_id", "trip_start_timestamp", "trip_end_timestamp"],
        keep=False
    )
].sort_values(["taxi_id", "trip_start_timestamp", "trip_end_timestamp"])

dup_taxi_time[
    [
        "trip_id", "taxi_id", "trip_start_timestamp", "trip_end_timestamp",
        "trip_seconds", "trip_miles", "fare", "trip_total",
        "payment_type", "company"
    ]
].head(30)

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,fare,trip_total,payment_type,company
205641,789df9ed9d6a2139febdc7ee3784e8eb219ced18,0041f8f0c91881c1e1913f2548522495fe3c4c719aa67f...,2024-01-11 13:45:00,2024-01-11 13:45:00,0.0,0.00,3.25,3.25,Cash,Taxi Affiliation Services
209880,7b1fb96fd071d6af1151437c6f1ae5ec959c5683,0041f8f0c91881c1e1913f2548522495fe3c4c719aa67f...,2024-01-11 13:45:00,2024-01-11 13:45:00,60.0,0.00,4.75,4.75,Cash,Taxi Affiliation Services
312991,b7ae5ea228d6ac282ba17d1310cd625b6ba16d73,0041f8f0c91881c1e1913f2548522495fe3c4c719aa67f...,2024-01-16 14:15:00,2024-01-16 14:15:00,0.0,0.00,3.25,3.25,Cash,Taxi Affiliation Services
414149,f2c96c504f553485b1b51a31c91fe503e7c0f0c9,0041f8f0c91881c1e1913f2548522495fe3c4c719aa67f...,2024-01-16 14:15:00,2024-01-16 14:15:00,240.0,0.00,5.00,5.00,Unknown,Taxi Affiliation Services
70564,294b58c308310f532e2a0df5668d8656718213d3,0041f8f0c91881c1e1913f2548522495fe3c4c719aa67f...,2024-01-19 17:15:00,2024-01-19 17:15:00,360.0,0.00,5.75,7.75,Credit Card,Taxi Affiliation Services
434358,fe9aa56aefb36b60d9cbf85b668492237f0c17ae,0041f8f0c91881c1e1913f2548522495fe3c4c719aa67f...,2024-01-19 17:15:00,2024-01-19 17:15:00,300.0,0.00,5.75,9.75,Credit Card,Taxi Affiliation Services
719817,a08e518dbbfc3eded542ba89f80b2dfa91bdeaa6,0041f8f0c91881c1e1913f2548522495fe3c4c719aa67f...,2024-02-20 14:00:00,2024-02-20 14:00:00,0.0,0.00,3.25,3.25,Cash,Taxi Affiliation Services
869042,f4e72fe120d8bd230a45f31720e2d601898634e5,0041f8f0c91881c1e1913f2548522495fe3c4c719aa67f...,2024-02-20 14:00:00,2024-02-20 14:00:00,180.0,0.00,4.25,4.25,Cash,Taxi Affiliation Services
459098,0cd3c0a0b6bf640ff934bf8f562450a96b805ec5,0041f8f0c91881c1e1913f2548522495fe3c4c719aa67f...,2024-02-28 19:00:00,2024-02-28 19:00:00,0.0,0.00,7.50,9.50,Credit Card,Taxi Affiliation Services
717995,9f8ff91834d5b9130aeb778c7919531ac6ae6e98,0041f8f0c91881c1e1913f2548522495fe3c4c719aa67f...,2024-02-28 19:00:00,2024-02-28 19:00:00,0.0,0.00,3.25,5.25,Cash,Taxi Affiliation Services
1148376,7a83bb78a0b45223b81c807c3dad9be6f73ff938,0041f8f0c91881c1e1913f2548522495fe3c4c719aa67f...,2024-03-19 16:30:00,2024-03-19 16:30:00,0.0,0.00,3.25,3.25,Cash,Taxi Affiliation Services
1320506,cb4e0e9410adde837981282e960f1643d0dce15f,0041f8f0c91881c1e1913f2548522495fe3c4c719aa67f...,2024-03-19 16:30:00,2024-03-19 16:30:00,60.0,0.00,3.25,3.25,Cash,Taxi Affiliation Services
937635,172dd60ab9859be1dd4857a0caa440931fba0597,0041f8f0c91881c1e1913f2548522495fe3c4c719aa67f...,2024-03-20 09:15:00,2024-03-20 09:15:00,0.0,0.00,3.25,3.25,Cash,Taxi Affiliation Services
1092891,604623d12852bc45518e73fb76c5182781afb245,0041f8f0c91881c1e1913f2548522495fe3c4c719aa67f...,2024-03-20 09:15:00,2024-03-20 09:15:00,0.0,0.00,3.25,4.25,Cash,Taxi Affiliation Services
976367,29491adecb443575ebe6ccb22e3724f587ef2af8,0041f8f0c91881c1e1913f2548522495fe3c4c719aa67f...,2024-03-21 06:30:00,2024-03-21 06:30:00,0.0,0.00,3.25,3.25,Cash,Taxi Affiliation Services
1089743,5ec9cc646407a85b1c9b607999ad10d90051bc42,0041f8f0c91881c1e1913f2548522495fe3c4c719aa67f...,2024-03-21 06:30:00,2024-03-21 06:30:00,0.0,0.00,3.25,3.25,Cash,Taxi Affiliation Services
912865,0b7a538c8904f41f021c98fdd93138347b78f71b,0041f8f0c91881c1e1913f2548522495fe3c4c719aa67f...,2024-03-22 07:30:00,2024-03-22 07:30:00,0.0,0.00,3.25,3.25,Cash,Taxi Affiliation Services
960363,21dd7b4976c3d3ba3445fe7b7525b63e360be0cd,0041f8f0c91881c1e1913f2548522495fe3c4c719aa67f...,2024-03-22 07:30:00,2024-03-22 07:30:00,0.0,0.00,3.25,3.25,Cash,Taxi Affiliation Services
1145861,79562da0b9aae47bfba6bbaa150324d3493b918f,0041f8f0c91881c1e1913f2548522495fe3c4c719aa67f...,2024-03-22 07:30:00,2024-03-22 07:30:00,0.0,0.00,3.25,3.25,Cash,Taxi Affiliation Services
919423,0eadd42a3736e22b9380b768420792192973861b,0041f8f0c91881c1e1913f2548522495fe3c4c719aa67f...,2024-03-26 12:30:00,2024-03-26 12:30:00,0.0,0.00,50.00,50.00,Cash,Taxi Affiliation Services
973115,27cd297b34993e54dd272eb1126644a3b3947214,0041f8f0c91881c1e1913f2548522495fe3c4c719aa67f...,2024-03-26 12:30:00,2024-03-26 12:30:00,60.0,0.00,3.25,3.25,Cash,Taxi Affiliation Services
1243712,a760892359f80cfaa083ac228c9dfac24f931931,0041f8f0c91881c1e1913f2548522495fe3c4c719aa67f...,2024-03-28 12:30:00,2024-03-28 12:30:00,420.0,0.10,7.25,7.25,Unknown,Taxi Affiliation Services
1300840,c21633ee0fd1ae60f13cee4717b2cf09e3b5dcfd,0041f8f0c91881c1e1913f2548522495fe3c4c719aa67f...,2024-03-28 12:30:00,2024-03-28 12:30:00,0.0,0.00,3.25,3.25,Cash,Taxi Affiliation Services
1549067,371e7789ac9828d6e5419aeddf86c6868b1a841a,0041f8f0c91881c1e1913f2548522495fe3c4c719aa67f...,2024-04-04 18:45:00,2024-04-04 19:00:00,624.0,1.82,10.00,12.58,Mobile,Tac - Yellow Cab Association
1945959,f36554e18644e555be7b86f08fb4a86450152c93,0041f8f0c91881c1e1913f2548522495fe3c4c719aa67f...,2024-04-04 18:45:00,2024-04-04 19:00:00,660.0,0.10,8.50,10.50,Credit Card,Taxi Affiliation Services
1528130,2d1bbdaa6a5f5a55557fbfefe92f8480a17cd5bf,0041f8f0c91881c1e1913f2548522495fe3c4c719aa67f...,2024-04-05 15:15:00,2024-04-05 15:15:00,540.0,0.00,8.25,11.25,Credit Card,Taxi Affiliation Services
1854892,c84e8ec1c8f7c8089ec05c9b8873317f3f257722,0041f8f0c91881c1e1913f2548522495fe3c4c719aa67f...,2024-04-05 15:15:00,2024-04-05 15:15:00,737.0,1.75,9.00,11.04,Mobile,Tac - Yellow Cab Association
1532225,2f1cc4d0c10caa70f1ae50bb4ae636dca8859b27,0041f8f0c91881c1e1913f2548522495fe3c4c719aa67f...,2024-04-05 18:45:00,2024-04-05 19:00:00,1140.0,0.20,12.50,15.75,Credit Card,Taxi Affiliation Services
1786130,a7d3e9f0bd3ceb70e44582d1cc54751100ea1495,0041f8f0c91881c1e1913f2548522495fe3c4c719aa67f...,2024-04-05 18:45:00,2024-04-05 19:00:00,441.0,1.38,10.00,11.00,Mobile,Tac - Yellow Cab Association
1610777,547b42d153644117ef13166ce99320212ccd4705,0041f8f0c91881c1e1913f2548522495fe3c4c719aa67f...,2024-04-10 19:15:00,2024-04-10 19:30:00,542.0,1.80,9.00,10.68,Mobile,Tac - Yellow Cab Association

In [62]:
dup_taxi_time.groupby(
    ["taxi_id", "trip_start_timestamp", "trip_end_timestamp"]
).size().sort_values(ascending=False).head(20)

taxi_id                                                                                                                           trip_start_timestamp  trip_end_timestamp
02ef8f01232b1b1828f4e5e1b8e8a85cd71b67c449afafbd2dd7ab726b2bb72795fcd00a9bb2477dfa6f8a325bbfde41ae888127ecd354096a1117f5e6fd9e0d  2024-12-30 01:15:00   2024-12-30 01:15:00    37
1faf8b812afc33b1e1a4f600e67a5a33f13ee8dd8ebf75922e70ffa1085bb6670ed097a30f9b15004f88b4fbee1efc9c029ffdd0d8712e0409469b7c799e433b  2026-02-14 12:45:00   2026-02-14 12:45:00    23
c8f57a1150c210a9e6b3fcfb24c3d6d0a43d1879b4b9795d12ffb5917f2b77c86a098c8f0a7c2a301ef4ea972985d4e05bd8d52a2f7a1ecca253fb8e81e5755e  2024-10-28 10:15:00   2024-10-28 10:15:00    15
222a0a55fe5180e292a8e128804e081fa50b05a0329775f9344b50ee230f23d12635ee6a2429af764d01221057af04260089849cfb0192fa29bfda38362ffad6  2024-03-09 10:45:00   2024-03-09 10:45:00    14
                                                                                                                                  2024-03-09 10:30:00   2024-03-09 10:30:00    13
a3e73cd26d232296ca0195222c3031b06c88603fc685681153648bc40c09160d7f7dba55445b7ea6acd55dbef07e75fcf155ff6da1bef621cb0b131658654b66  2024-09-26 10:00:00   2024-09-26 10:00:00    12
fbfc2ff558d0fc2dd96362ef65d25e08f00b13bc427645692cc034fb62d0ccf5f19c7187554fdf79c714323023b793de64da10de48051c38528f05ca5fc29e27  2024-02-02 15:00:00   2024-02-02 15:00:00    12
e3a458804fe9298cd1ab49287e64a8a8354d9a0766f0628b77a864d7d987dfed6813002c51dbb836288e24fe7afdc33bdc5a2fba6b1d25caaf04a0a6866f3aa5  2024-02-19 14:45:00   2024-02-19 15:00:00    12
d156d4adff01addd62b65753ce67dc8e04bdaf60f7eb14a4a557f54062e2fc83ca1ebe1bf2cd9eb7aac4a12707cb5aa3e915d9fe1e729dfb5fa5657659e11eab  2024-01-11 09:45:00   2024-01-11 09:45:00    12
c8f57a1150c210a9e6b3fcfb24c3d6d0a43d1879b4b9795d12ffb5917f2b77c86a098c8f0a7c2a301ef4ea972985d4e05bd8d52a2f7a1ecca253fb8e81e5755e  2024-10-28 10:30:00   2024-10-28 10:30:00    12
b3ee94a13b61037620cbbfc6a4a106d2ad628a06f0988f1eba5586d5387776d3781d71244392ff9c1afd5b69e65dfec45b2a936c2d101209044ff6365121ed6f  2025-02-06 18:15:00   2025-02-06 18:15:00    12
c8f57a1150c210a9e6b3fcfb24c3d6d0a43d1879b4b9795d12ffb5917f2b77c86a098c8f0a7c2a301ef4ea972985d4e05bd8d52a2f7a1ecca253fb8e81e5755e  2024-10-22 09:15:00   2024-10-22 09:15:00    11
68aae28119a6c274b4957fa18111a0883d0c433381d52e173d0571d340ddab1de60a68ee6aa19ce8d0e1f34cb653a202f563861123a947e3f019cce0c024271e  2024-08-08 08:00:00   2024-08-08 08:15:00    11
3618045f9110d4d88482266ade23659c1a50d32ac37f205c15614b1ada9d4ca14b171329afed5dfd81c7525bd5a05fe614cb63b2aa48d920626b519e20d9e146  2024-06-13 17:45:00   2024-06-13 17:45:00    11
c934ff21f441a86be68e3fd50456cf428e23ad795305c5ce8b6df993254175c0c99d66a193994334313dcaa9ec8c4c69701fd2fa3640914115d100049a7ca81a  2024-05-31 09:30:00   2024-05-31 09:30:00    11
                                                                                                                                  2024-04-20 13:45:00   2024-04-20 13:45:00    11
02ef8f01232b1b1828f4e5e1b8e8a85cd71b67c449afafbd2dd7ab726b2bb72795fcd00a9bb2477dfa6f8a325bbfde41ae888127ecd354096a1117f5e6fd9e0d  2024-12-30 01:30:00   2024-12-30 01:30:00    11
71299f519d81a7d3bd0fd6bb0d0f8ebd553ea3a851d0716b354091e93567cf9b964e9fc31976baa285d14cb41ec9a10b827266f66a1261aaaac00d542b2eec81  2024-01-15 11:45:00   2024-01-15 12:00:00    11
c8f57a1150c210a9e6b3fcfb24c3d6d0a43d1879b4b9795d12ffb5917f2b77c86a098c8f0a7c2a301ef4ea972985d4e05bd8d52a2f7a1ecca253fb8e81e5755e  2024-10-28 10:45:00   2024-10-28 10:45:00    11
                                                                                                                                  2024-10-16 09:00:00   2024-10-16 09:00:00    10
dtype: int64

In [63]:
(df["trip_seconds"] == 0).sum()

np.int64(195154)

EXPORT PARQUET para total y CSV para 2026

In [ ]:
#   df.to_parquet(DATA_STAGING / "taxi_trips_chicago_staging.parquet", index=False)

In [66]:
#   # ME QUEDO CON EL 2026 PARA TRAGBAJAR EN DASHBOARDS
#   df_2026 = df[df["trip_year"] == 2026].copy()
#   
#   df_2026.to_csv(DATA_STAGING / "taxi_trips_chicago_2026.csv", index=False)